In [1]:
import sys
print(sys.version)

import tensorflow as tf
print(tf.__version__)

import numpy as np

3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:52:09) 
[Clang 14.0.6 ]
2.12.0


In [2]:
"""
1. 范数
tf.orm(tensor, ord, axis)
tensor表示需要求范数的张量；ord=1求一范数，ord=2求二范数，默认求二范数；axis指定轴，按照哪个轴求范数，默认求整个张量的范数

一范数： 绝对值之和      二范数： 平方和再开根   
"""
# 创建一个二维tensor
a = tf.constant([[1,2],[3,4]],dtype=tf.float32)
print(a)
# ==1== 求一个tensor的二范数
print(tf.norm(a)) # ord可省略，默认二范数
# ==2== 求一个tensor某一个轴的二范数
print(tf.norm(a,ord=2,axis=1))  # 在第1个维度【列】上求，每一行的平方和开根
# ==3== 求一个tensor的一范数
print(tf.norm(a,ord=1))  # 每个元素的绝对值之和
# ==4== 求一个tensor指定轴上的一范数
print(tf.norm(a,ord=1,axis=0)) # 在第0个维度【行】上求，每一列的绝对值之和
"""
tf.norm(a) 是对a的所有元素都求平方再相加再开根，即 
tf.norm(a,ord=2,axis=1) 是指定在第1个轴上求二范数，也就是对最外层括号里面的内容，即分别对 [1,2] 和 [3,4] 求二范数，返回[2.23, 5]
tf.norm(a,ord=1) 没指定轴，求整个张量的一范数，绝对值之和，即1+2+3+4=10
tf.norm(a,ord=1,axis=0) 对第0个轴求一范数，即分别对 [1,3] 和 [2,4] 求一范数。即[4,6]
"""

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
tf.Tensor(5.477226, shape=(), dtype=float32)
tf.Tensor([2.236068 5.      ], shape=(2,), dtype=float32)
tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([4. 6.], shape=(2,), dtype=float32)


In [67]:
"""
2. 最值、均值
最小值  tf.reduce_min()； 最大值  tf.reduce_max()； 均值  tf.reduce_mean()
参数均为：tensor 需要计算的张量；axis 指定计算的轴

2.1 若不指定轴，计算的是整个tensor的最值和均值
"""
# 3行5列的每个元素在0-20中随机选取，元素是整型
a = tf.random.uniform([3,5],minval=0,maxval=20,dtype=tf.int32)
print(a)
# ==1== 不指定轴axis
print(tf.reduce_min(a))  # 求整个tensor的最小值，变成了0维
print(tf.reduce_max(a))
print(tf.reduce_mean(a))
"""
求最值、均值时会有一个降维过程，比如这里的二维tensor，不指定轴求整个tensor的最值、均值，返回值是一个标量，这就是一个降维的过程。
"""

tf.Tensor(
[[18 17  4  0  1]
 [ 4 10 17 11 19]
 [14  7  6  7 17]], shape=(3, 5), dtype=int32)
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor(19, shape=(), dtype=int32)
tf.Tensor(10, shape=(), dtype=int32)


In [77]:
"""
2.2 若指定轴
"""
#2个图，3行，5列
a = tf.random.uniform([2,3,5],minval=0,maxval=20,dtype=tf.int32)
print(a)
# ==2== 指定轴axis
# 求每一图的最小值
print(tf.reduce_min(a,axis=0))
# 求每一行的最大值
print(tf.reduce_max(a,axis=2))
# 求每一列的均值
print(tf.reduce_mean(a,axis=1))

tf.Tensor(
[[[ 7  9 12  8 18]
  [ 0  5  4  0 13]
  [ 1  0  4  6  5]]

 [[16  0  2  7 10]
  [ 9  3  6 10  3]
  [13  8 17  2  3]]], shape=(2, 3, 5), dtype=int32)
tf.Tensor(
[[ 7  0  2  7 10]
 [ 0  3  4  0  3]
 [ 1  0  4  2  3]], shape=(3, 5), dtype=int32)
tf.Tensor(
[[18 13  6]
 [16 10 17]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[ 2  4  6  4 12]
 [12  3  8  6  5]], shape=(2, 5), dtype=int32)


In [80]:
"""
3. 最值的位置
最大值的索引位置： tf.argmax()      最小值的索引位置： tf.argmin()
参数： tensor 需要计算的张量；axis 指定计算的轴
"""
# 2图3行5列的每个元素在0-20中随机选取，元素是整型
a = tf.random.uniform([2,3,5],minval=0,maxval=20,dtype=tf.int32)
print(a)
# 最大值位置
print(tf.argmax(a))  # 默认axis=0，即在第0个维度上求最大值所在位置
# 最小值位置
print(tf.argmin(a,axis=1))  # 在第1的维度上求最小值所在位置

tf.Tensor(
[[[ 4  6 15  2 16]
  [ 4 11 17  7  6]
  [ 0  9 11  4 10]]

 [[ 5  4  1 19 12]
  [11 16  2  9  2]
  [13 18  8 19  6]]], shape=(2, 3, 5), dtype=int32)
tf.Tensor(
[[1 0 0 1 0]
 [1 1 0 1 0]
 [1 1 0 1 0]], shape=(3, 5), dtype=int64)
tf.Tensor(
[[2 0 2 0 1]
 [0 0 0 1 1]], shape=(2, 5), dtype=int64)


In [83]:
"""
4. 判断相同元素
tf.equal(tensor1, tensor2)
判断两个tensor变量是否相等，它的判断方法不是整体判断，而是逐个元素进行判断，如果相等就是True，不相等，就是False。
"""
a = tf.constant([1,2,3,4,5])
b = tf.constant([5,4,3,2,1])
print(a)
print(b)
# 比较，相同返回True
print(tf.equal(a,b))
"""
通过对a和b的每一个元素两两相比较，只有3是同位置同数值，返回True，其他都是False。
"""

print('==================================================================================================================================')

"""
当我们比较两幅数据量很大的图像时，可以通过返回值来计算有几个相同的元素
首先利用类型转换函数cast()，将布尔类型转换成整型，再通过求和函数tf.reduce_sum()来计算个数。我们通过这个思路来计算这两个tensor有几个相同的元素。最终返回数值1。
"""
a = tf.constant([1,2,3,4,5])
b = tf.constant([5,4,3,2,1])
# 接收布尔返回值
res = tf.equal(a,b)
print(res)
# 计算两个tensor有几个相同的元素
# 将res中的布尔类型转换成整型
print(tf.cast(res,dtype=tf.int32))
print(tf.reduce_sum(tf.cast(res,dtype=tf.int32)))

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
tf.Tensor([5 4 3 2 1], shape=(5,), dtype=int32)
tf.Tensor([False False  True False False], shape=(5,), dtype=bool)
tf.Tensor([False False  True False False], shape=(5,), dtype=bool)
tf.Tensor([0 0 1 0 0], shape=(5,), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


In [84]:
"""
5. 求唯一值
tf.unique(tensor)
返回tensor变量中的互不相同的值组成的列表，和原值的每个元素在唯一值列表中的位置
"""
# 创建一个一维列表
a = tf.constant([5,6,7,8,6,5])
# 返回唯一值、和原数据中的每个元素在唯一值列表中的索引位置
res,arr = tf.unique(a)
print(res)
print(arr)

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor([0 1 2 3 1 0], shape=(6,), dtype=int32)


In [87]:
"""
6. 求和
tf.reduce_sum(tensor, axis)
对tensor变量求和，若不指定axis轴，默认求整个tensor变量的所有元素的和
"""
# 创建一个3行5列，每个元素都是在0-4之间随机取
a = tf.random.uniform([3,5],minval=0,maxval=5,dtype=tf.int32)
print(a)
# 整个tensor变量的和
print(tf.reduce_sum(a))
# 对第0个轴求和
print(tf.reduce_sum(a,axis=0))
# 对第1个轴求和
print(tf.reduce_sum(a,axis=1))

tf.Tensor(
[[3 1 4 4 2]
 [1 3 0 0 3]
 [1 1 3 1 0]], shape=(3, 5), dtype=int32)
tf.Tensor(27, shape=(), dtype=int32)
tf.Tensor([5 5 7 5 5], shape=(5,), dtype=int32)
tf.Tensor([14  7  6], shape=(3,), dtype=int32)
