In [2]:
import sys
print(sys.version)

import tensorflow as tf
print(tf.__version__)

import numpy as np

3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:52:09) 
[Clang 14.0.6 ]
2.12.0


In [3]:
"""
1. 给定每一维度的索引获取数据
1.1 变量[ ][ ] 方法
首先定义一个全为1的四维tensor，如：tf.ones([2,3,3,2])。由于整个数据庞大，不利于观察，我们使用.shape来观察取出数据的情况。
"""
#创建一个全为1的四维tensor，默认float32
a = tf.ones([2,3,3,2])
print(a)
# 返回3，3，2的tensor  
print(a[0].shape) 
#取出3行2列的矩阵tensor
print(a[0][0].shape)  
#返回长度为2列表tensor
print(a[0][0][0].shape) 
#值为标量1，是0维tensor.
print(a[0][0][0][1].shape)  

tf.Tensor(
[[[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]


 [[[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]

  [[1. 1.]
   [1. 1.]
   [1. 1.]]]], shape=(2, 3, 3, 2), dtype=float32)
(3, 3, 2)
(3, 2)
(2,)
()


In [4]:
"""
1.2 变量[ , ] 方法
"""
#创建一个四维随机正态分布tensor
a = tf.random.normal([4,5,6,7])  
print(a)
# 
print(a[1].shape)  # 返回[5,6,7]
# 
print(a[1,2].shape)  # 返回[6,7]
#
print(a[1,2,3].shape)  # 返回[7]
# 
print(a[1,2,3,4])  # 返回值

tf.Tensor(
[[[[ 1.4501307  -0.18327013  0.06213326  0.8096377   1.4903556
     0.35950944  0.14453143]
   [-0.59148246 -0.43862522 -0.13565344  1.4478565  -0.02019188
    -0.65759057  1.0876904 ]
   [-0.12442809 -0.52004385  1.4663012  -0.45184243 -1.3558346
     0.013488   -1.6366688 ]
   [-0.66865695 -1.4166441   0.02994437  0.6745481  -0.30124006
    -1.6169149  -0.073172  ]
   [-0.15182917  0.6142618   2.474899    0.1777907   0.16200627
     1.1142519   0.5315702 ]
   [ 0.59207505  0.6160611  -0.7045144  -0.89884865 -0.01121286
     1.5617422   1.0492854 ]]

  [[-1.4457453  -0.6343925  -1.1075029  -0.89496756 -1.5125253
     1.2704539  -1.6230316 ]
   [ 0.84499943 -0.6744958  -1.7995518  -1.168703    1.1106421
     1.1181366  -1.2733014 ]
   [ 1.036264   -0.2983345  -1.2290267  -0.45471284  0.29662392
    -0.39220697  0.09359588]
   [ 2.2349324   0.8295196  -0.15351374  0.07994271  1.5817947
     0.71787316  0.10132119]
   [ 0.58440197  0.52459663  2.1874316   1.4785554  -0.3006687

In [5]:
"""
2. 切片索引
2.1 变量[start : end]
使用位置索引切片，顾头不顾尾
"""
# ==1== 方法一
 #从0-9的10个元素组成的tensor
a = tf.range(10)
print(a)
# 获取3、4、5
print(a[3:6])
# 获取前3个，0、1、2
print(a[:3])
# 获取倒数第4个到倒数第2个，-1代表最后一个
print(a[-4:-1])

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)
tf.Tensor([3 4 5], shape=(3,), dtype=int32)
tf.Tensor([0 1 2], shape=(3,), dtype=int32)
tf.Tensor([6 7 8], shape=(3,), dtype=int32)


In [11]:
"""
2.2 多个冒号，变量[A , : , : , B]
"""
# ==2== 方法二
#创建4维tensor
b = tf.ones([4,5,6,7]) 
print(b)
# # 第0张图像有5行，每行有6列，每列有7个数
# print(b[0].shape)  
# # 取第0张图片的所有数据
# print(b[0,:,:,:].shape)
# # 变成单通道，前3个维度全部获取，第四个维度取第2个
# print(b[:,:,:,2].shape) 
# # 4张图像都取第2行，每行的所有列，每列的所有值，shape[4,6,7]
# print(b[:,2,:,:].shape)

tf.Tensor(
[[[[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]]


 [[[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 1. 1. 1. 1.]]

  [[1. 1. 1. 1. 1. 1. 1.]
   [1. 1. 1. 

In [32]:
"""
2.3 指定步长，隔行采样，变量[start : end : step]
"""
# 定义四维且值全为1的tensor
c = tf.ones([5,6,7,8]) 
# print(c)
# 第1、3张图像的所有数据
print(c[1:5:2,:,:,:].shape)
# 5张图片图片的第1、3行，0、2列的所有数据
print(c[:,1:5:2,:4:2,:].shape)
print('==================================================================================================================================')

"""
步长为负数时，要求A靠近原数据尾端，B是前端
逆序排序方法： 变量 [A : B : -1]
"""
# ==4== 逆序排序
#创建0-4的tensor
d = tf.range(5) 
print(d)
print(d[:4:2])
print(d[4:0:-2])

# 给d逆序排序
print(d[::-1])
# 倒序：4、2、0
print(d[4::-2])


(2, 6, 7, 8)
(5, 2, 2, 8)
tf.Tensor([0 1 2 3 4], shape=(5,), dtype=int32)
tf.Tensor([0 2], shape=(2,), dtype=int32)
tf.Tensor([4 2], shape=(2,), dtype=int32)
tf.Tensor([4 3 2 1 0], shape=(5,), dtype=int32)
tf.Tensor([4 2 0], shape=(3,), dtype=int32)


In [33]:
"""
3. 省略号 '...' 方法
相比于 变量[ A , : , : , : , B]，变量 [ A , ... , B ] 中，省略号自动计算A和B之间有几个':'，写起来更方便。
首先创建一个五维tensor，形状shape为[3,10,12,14,8]，其中 a[0] 和 a[0 , : , : , : , : ] 和 a[0 , ...] 代表的意思相同，都是指第一张图像的全部数据。
shape为[10,12,14,8]
"""
# 创建一个五维tensor
a = tf.random.normal([3,10,12,14,8]) 
# 第0张图像的所有数据
print(a[0].shape)
print(a[0,:,:,:,:].shape)  # 和上式相同  
print(a[0,...].shape)  # 省略号代表后面的冒号
# 省略号代表中间两维
print(a[0,...,4,:].shape)

(10, 12, 14, 8)
(10, 12, 14, 8)
(10, 12, 14, 8)
(10, 12, 8)


In [34]:
"""
4. tf.gather()函数
指定某一个维度，按照指定索引获取数据
tf.gather(tensor, axis, indices=[ ])
value：代表tensor数据
axis： 代表取哪个维度
indices： 数据收集顺序，指定维度的具体索引

4.1 使用一次 tf.gather()
创建一个三维的data全由0构成，shape为[4,35,8]，可以理解为4个班级，每个班级35个人，每个人有8门功课。指定一个维度，获得该维度下其他维度的部分数据。
axis用来指定维度，axis=0代表班级维度，axis=1代表学生，axis=2代表功课。
"""
# 假设data三维[班级,学生,科目]
data = tf.zeros([4,35,8])
# indices指定收集顺序，查第2、3个班级的所有数据
print(tf.gather(data,axis=0,indices=[2,3]).shape)
# 指定维度1即学生，收集索引号维30、5、18、2这四个学生的数据
print(tf.gather(data,axis=1,indices=[30,5,18,2]).shape)

(2, 35, 8)
(4, 4, 8)


In [35]:
"""
4.2 连续使用几次 tf.gather()
上面是获取指定维度指定索引的全部数据。如果我想获取指定维度指定索引的指定数据怎么办呢。
我们连续使用两次tf.gather()来抽查，所有班级某几位同学的某几门课的成绩
"""
# 获得四个班级指定三名学生的指定的三门课信息
data = tf.zeros([4,35,8])
a1 = tf.gather(data,axis=1,indices=[30,5,18,2])  #获取4名学生的全部信息
print(a1)
a2 = tf.gather(a1,axis=2,indices=[6,1,4]).shape  #axis=2指定科目，获取6，1，4科目信息
print(a2)

tf.Tensor(
[[[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0. 0.]]], shape=(4, 4, 8), dtype=float32)
(4, 4, 3)


In [37]:
"""
5. tf.gather_nd() 函数
tf.gather_nd(tensor, indices)
按照 indices 的格式从传入的tensor中抽取切片（合并为一个Tensor）indices是一个K维整数Tensor

首先创建一个三维且值全为0的tensor，可按上述方法理解这三维。
"""
# 指定2个维度，取第三个维度的所有值
data = tf.zeros([4,35,8])
# 获取第[[0]]个班级所有数据，返回值减少一维度
a1 = tf.gather_nd(data,[0]).shape  
print(a1)
# 取0号班级第1个学生的数据，返回值少两个维度
a2 = tf.gather_nd(data,[0,1]).shape
print(a2)
# 取0号班级第1个学生的第2门课的数据，返回值少三个维度
a3 = tf.gather_nd(data,[0,1,2]).shape
print(a3)
print('==================================================================================================================================')


"""
注意参数indices的括号使用方法，如a5，首先获取第0个班级的第1个学生的功课数据（一维），第1个班级第5个学生的功课数据（一维），2个列表组合放到一个列表里，组成二维列表，
再在外面加一个中括号，生成三维，理解为这是第1次抽取结果，因此返回的shape为[1,2,8]

再如a6，获取的是指定班级指定学生的功课信息，[0,4]指第0个班级第4位同学的所有功课数据，返回一个列表（一维），由8门功课组成。三个一维列表外面加一个中括号，构成二维列表。
shape维[3,8]。指有3位同学，每位同学有8门课。
"""
# 取第0个班级的第1名学生的第2门课成绩，和第1个班级的第5名学生的第7门课成绩，放在一个列表中
a4 = tf.gather_nd(data,[[0,1,2],[1,5,7]]).shape
print(a4)
# 取第0个班级的第1名学生的所有课成绩，和第1个班级的第5名学生的所有课成绩
a5 = tf.gather_nd(data,[[[0,1],[1,5]]]).shape 
print(a5)
# 将二维的成绩信息放在一个三维tensor中，
# 第一维表示第一次记录，第二维表示哪些学生，第三维表示每个学生的所有科目
# 第0个班级的第4个学生的所有科目，第1个班级第7个学生所有科目。。。组合成一个二维tensor"""
a6 = tf.gather_nd(data,[[0,4],[1,7],[3,5]]).shape
print(a6)

(35, 8)
(8,)
()
(2,)
(1, 2, 8)
(3, 8)


In [4]:
"""
6. 布尔索引选数据
tf.boolean_mask(tensor, mask=布尔标记, axis=指定维度)
mask的shape要和指定维度的tensor的shape相同。输出mask标记维True的值。
"""
# 选择输出mask为True的值
a = tf.ones([3,35,5,10]) # 3个班级35名学生5门课各有10份作业
# 对第0维的3个班级生成mask，即值要第0、1个班级的数据
print(tf.boolean_mask(a,mask=[True,True,False]).shape)  #默认axis=0，即第一个维度
# 对第2维的课目生成mark，要第2、3门课的所有信息
print(tf.boolean_mask(a,mask=[False,False,True,True,False],axis=2).shape)
### tf.boolean_mask(a,mask=[True,True,False]).shape 
### 对班级维度的三个班级进行选择，第0、1个班级为True，第2个班级为False，因此输出第0、1个班级的全部信息，即shape为[2,35,5,10]

print('==================================================================================================================================')

"""
生成一个三维的值全为1的tensor，没有指定axis，可看出是对班级维度和学生维度的筛选。输出结果的第一行是第0个班级第0个学生的4项信息，
结果的第二三行是第1个班级第1、2个学生的四项信息。
"""
b = tf.ones([2,3,4])
print(b)
# mask对应b的前两维度，第0维度取第0列的所有数据，第1维度取第1、2列的所有数据
print(tf.boolean_mask(b,mask=[[True,False,False],[False,True,True]]))
"""
Question?
为什么，第0个班级的第0个学生和第1个班级的第1，2个学生会合并成为一个维度？
"""
print(tf.gather_nd(b,[[0,0,0],[1,1,2],[1,2,3]]))

(2, 35, 5, 10)
(3, 35, 2, 10)
tf.Tensor(
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]], shape=(2, 3, 4), dtype=float32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(3, 4), dtype=float32)
tf.Tensor([1. 1. 1.], shape=(3,), dtype=float32)
